version: '3.8'

services:
  demo-page:
    build: .
    ports:
      - "4000:4000"
    env_file:   
      - .env 
    networks:
      - pg_postgres-network

networks:
  pg_postgres-network:
    external: true
